FROM openjdk:8-jdk-alpine
WORKDIR /work
COPY ./target/StudentDetails-0.0.1-SNAPSHOT.jar studentdetails.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/work/studentdetails.jar"]